/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aula05;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Roger
 */
public class Exercicio04 extends javax.swing.JFrame {

    int[] idades = new int[10];
    int contador = 0;
    
    
    /**
     * Creates new form Exercicio04
     */
    public Exercicio04() {
        initComponents();
    }
    
    private int descobrirMaiorIdade(){
        
        int maior = idades[0];
        
        for (int i = 1; i < idades.length; i++) {
            if (idades[i] > maior)
                maior = idades[i];
        }
        
        return maior;
    }
    
    private int descobrirMenorIdade(){
        
        int menor = idades[0];
        
        for (int i = 1; i < idades.length; i++) {
            if (idades[i] < menor)
                menor = idades[i];
        }
        
        return menor;
    }
    
    private int calcularMedia(){
        
        int soma = 0;
        
        for (int idade : idades) {
            soma+=idade;
        }
        
        return soma / idades.length;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdade = new javax.swing.JTextField();
        labelIdade = new javax.swing.JLabel();
        botaoIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelIdade.setText("Informe a idade da 1ª pessoa:");

        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIncluir)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdade)
                    .addComponent(botaoIncluir))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        
        try
        {
            int idade = Integer.parseInt(txtIdade.getText());
            idades[contador] = idade;
            contador++;
            
            if (contador == 10){                
                JOptionPane.showMessageDialog(this, String.format("Média: %s %nMenor idade: %s %nMaior idade: %s", calcularMedia(), descobrirMenorIdade(), descobrirMaiorIdade()));
                System.exit(0);
            }          
            
            labelIdade.setText(String.format("Informe a idade da %sª pessoa:", contador + 1));
            txtIdade.setText("");
            txtIdade.requestFocus();
        }
        catch(NumberFormatException | HeadlessException ex)
        {
            JOptionPane.showMessageDialog(this, "Digite a idade em anos!");
        }        
    }//GEN-LAST:event_botaoIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JTextField txtIdade;
    // End of variables declaration//GEN-END:variables
}
