/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.aula05;

import javax.swing.JOptionPane;

/**
 *
 * @author Roger
 */
public class Exercicio03 extends javax.swing.JFrame {

    String[] produtos = new String[10];
    float[] valores = new float[10];
    
    /**
     * Creates new form Exercicio03
     */
    public Exercicio03() {
        
        produtos[0] = "Camiseta";
        produtos[1] = "Calça";
        produtos[2] = "Boné";
        produtos[3] = "Caneca";
        produtos[4] = "Poster";
        produtos[5] = "Miniatura Alien Power Loader";
        produtos[6] = "Miniatura Millenium Falcon";
        produtos[7] = "Vinil do Los Hermanos";
        produtos[8] = "Pneu aro 13";
        produtos[9] = "Gardenal 100 ML";
        
        valores[0] = 10.5f;
        valores[1] = 20.4f;
        valores[2] = 39.99f;
        valores[3] = 45.30f;
        valores[4] = 5.55f;
        valores[5] = 240f;
        valores[6] = 560.99f;
        valores[7] = 20.99f;
        valores[8] = 300f;
        valores[9] = 45f;
        
        initComponents();
        for (String produto : produtos) {
            comboItem1.addItem(produto);
            comboItem2.addItem(produto);
            comboItem3.addItem(produto);
            comboItem4.addItem(produto);
            comboItem5.addItem(produto);
        }        
    }
    
    private int getIndexProduto(String nome){
        for (int i = 0; i < produtos.length; i++) {
            if(produtos[i].equals(nome))
                return i;
        }
        
        return -1;
    }
    
    private float getValueProduto(int index){
        return valores[index];
    }
    
    private int getIntFromText(String text){
        try
        {
            return Integer.parseInt(text);            
        }
        catch(Exception ex)
        {
            return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        comboItem1 = new javax.swing.JComboBox<>();
        comboItem2 = new javax.swing.JComboBox<>();
        comboItem3 = new javax.swing.JComboBox<>();
        comboItem4 = new javax.swing.JComboBox<>();
        comboItem5 = new javax.swing.JComboBox<>();
        labelProdutos = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        textQtd1 = new javax.swing.JTextField();
        textQtd2 = new javax.swing.JTextField();
        textQtd3 = new javax.swing.JTextField();
        textQtd4 = new javax.swing.JTextField();
        textQtd5 = new javax.swing.JTextField();
        botaoFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelTitulo.setText("CARRINHO DE COMPRAS");

        comboItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItem3ActionPerformed(evt);
            }
        });

        labelProdutos.setText("Produtos");

        labelQuantidade.setText("Quantidade");

        textQtd1.setText("0");

        textQtd2.setText("0");

        textQtd3.setText("0");

        textQtd4.setText("0");

        textQtd5.setText("0");

        botaoFinalizar.setText("Finalizar Compra");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoFinalizar)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProdutos)
                                    .addComponent(comboItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(3, 3, 3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comboItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textQtd1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textQtd2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textQtd5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textQtd4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textQtd3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProdutos)
                    .addComponent(labelQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQtd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQtd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQtd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQtd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textQtd5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(botaoFinalizar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItem3ActionPerformed

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        
        float total = 0;

        int qtd01 = getIntFromText(textQtd1.getText());
        int qtd02 = getIntFromText(textQtd2.getText());
        int qtd03 = getIntFromText(textQtd3.getText());
        int qtd04 = getIntFromText(textQtd4.getText());
        int qtd05 = getIntFromText(textQtd5.getText());

        total += qtd01 * getValueProduto(getIndexProduto(comboItem1.getSelectedItem().toString()));
        total += qtd02 * getValueProduto(getIndexProduto(comboItem2.getSelectedItem().toString()));
        total += qtd03 * getValueProduto(getIndexProduto(comboItem3.getSelectedItem().toString()));
        total += qtd04 * getValueProduto(getIndexProduto(comboItem4.getSelectedItem().toString()));
        total += qtd05 * getValueProduto(getIndexProduto(comboItem5.getSelectedItem().toString()));

        JOptionPane.showMessageDialog(this, String.format("Tota da compra: R$ %.2f", total));
    }//GEN-LAST:event_botaoFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JComboBox<String> comboItem1;
    private javax.swing.JComboBox<String> comboItem2;
    private javax.swing.JComboBox<String> comboItem3;
    private javax.swing.JComboBox<String> comboItem4;
    private javax.swing.JComboBox<String> comboItem5;
    private javax.swing.JLabel labelProdutos;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textQtd1;
    private javax.swing.JTextField textQtd2;
    private javax.swing.JTextField textQtd3;
    private javax.swing.JTextField textQtd4;
    private javax.swing.JTextField textQtd5;
    // End of variables declaration//GEN-END:variables
}
