/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aula05;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Roger
 */
public class Exercicio08 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio08
     */
    public Exercicio08() {
        initComponents();
        listaFilmes.setModel(new DefaultListModel());
        random = new Random(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInclusao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoNota = new javax.swing.JTextField();
        botaoIncluir = new javax.swing.JButton();
        panelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFilmes = new javax.swing.JList<>();
        botaoLimpar = new javax.swing.JButton();
        botaoRecomendar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInclusao.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Filmes"));

        jLabel2.setText("Nome:");

        jLabel3.setText("Nota:");

        botaoIncluir.setText("INCLUIR");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInclusaoLayout = new javax.swing.GroupLayout(panelInclusao);
        panelInclusao.setLayout(panelInclusaoLayout);
        panelInclusaoLayout.setHorizontalGroup(
            panelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInclusaoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNota, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoIncluir))
        );
        panelInclusaoLayout.setVerticalGroup(
            panelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInclusaoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelInclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoIncluir))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        panelLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Filmes"));

        jScrollPane1.setViewportView(listaFilmes);

        botaoLimpar.setText("LIMPAR LISTA");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoRecomendar.setText("RECOMENDAÇÃO DE FILME");
        botaoRecomendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecomendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addComponent(botaoRecomendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimpar)
                    .addComponent(botaoRecomendar)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ORGANIZADOR DE FILMES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelInclusao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        incluirFilme(textoNome.getText(), textoNota.getText());
        textoNome.setText("");
        textoNota.setText("");
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoRecomendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecomendarActionPerformed
        recomendarFilmeAleatorio();
    }//GEN-LAST:event_botaoRecomendarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        listaFilmes.setModel(new DefaultListModel());
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void incluirFilme(String nomeNovoFilme, String notaNovoFilme){
        
        if (!validarNota(notaNovoFilme))
        {
            JOptionPane.showMessageDialog(this, "A nota deve ser um valor númérico.");
            return;
        }
        
        boolean jaIncluido = false;
        
        for (int i = 0; i < listaFilmes.getModel().getSize(); i++) {
            
            String filme = listaFilmes.getModel().getElementAt(i);
            String nomeFilme = filme.substring(0, filme.lastIndexOf("|"));
                    
            if (nomeNovoFilme.trim().equalsIgnoreCase(nomeFilme.trim())){
                JOptionPane.showMessageDialog(this, "Filme já incluído.");
                jaIncluido = true;
                break;
            }
        }
        
        if(jaIncluido)
            return;
          
        DefaultListModel model = (DefaultListModel)listaFilmes.getModel();
        if (model == null)
        {
            model = new DefaultListModel();
            listaFilmes.setModel(model);
        }
        
        model.addElement(String.format("%s | %s", nomeNovoFilme, notaNovoFilme));
    }
    
    private boolean validarNota(String nota){
        try
        {
            Float.parseFloat(nota);
            return true;
        }
        catch(Exception ex)
        {
            return false;
        }
    }
    
    private void recomendarFilmeAleatorio(){        
        JOptionPane.showMessageDialog(this, 
                String.format("Sugestão de filme: %s", 
                        listaFilmes
                                .getModel()
                                .getElementAt(random
                                        .nextInt(listaFilmes
                                                .getModel()
                                                .getSize()))));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio08().setVisible(true);
            }
        });
    }

    private Random random;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoRecomendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaFilmes;
    private javax.swing.JPanel panelInclusao;
    private javax.swing.JPanel panelLista;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoNota;
    // End of variables declaration//GEN-END:variables
}
