/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aula05;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Roger
 */
public class Exercicio05 extends javax.swing.JFrame {

    int pontuacaoJogador = 0;
    int pontuacaoComputador = 0;
    String[] jogadas = new String[3];
    Random random = new Random(0);
    
    /**
     * Creates new form Exercicio05
     */
    public Exercicio05() {
        initComponents();
        jogadas[0] = "PEDRA";
        jogadas[1] = "PAPEL";
        jogadas[2] = "TESOURA";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboEscolha = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        botaoJogar = new javax.swing.JButton();
        labelPontuacaoJogador = new javax.swing.JLabel();
        labelPontuacaoComputador = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PEDRA, PAPEL E TESOURA");

        comboEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEDRA", "PAPEL", "TESOURA" }));

        jLabel2.setText("Sua jogada:");

        botaoJogar.setText("JOGAR!");
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        labelPontuacaoJogador.setText("Você: 0");

        labelPontuacaoComputador.setText("Computador: 0");

        jLabel5.setText("PONTUAÇÃO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPontuacaoJogador)
                                .addGap(31, 31, 31)
                                .addComponent(labelPontuacaoComputador))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoJogar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel5)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(botaoJogar))
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPontuacaoJogador)
                    .addComponent(labelPontuacaoComputador))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
       int jogadaJogador = comboEscolha.getSelectedIndex();
       int jogadaComputador = random.nextInt(3);
       
        System.out.println("V:" + jogadaJogador);
        System.out.println("C:" + jogadaComputador);
               
       if (jogadaJogador == jogadaComputador){
           JOptionPane.showMessageDialog(this, String.format("Computador jogou %s. Empate.", jogadas[jogadaComputador]));
       }
       else if (jogadaComputador > jogadaJogador || (jogadaComputador == 0 && jogadaJogador == 2)){
           JOptionPane.showMessageDialog(this, String.format("Computador jogou %s. Ponto para o computador.", jogadas[jogadaComputador]));
           pontuacaoComputador++;
           labelPontuacaoComputador.setText(String.format("Computador: %s", pontuacaoComputador));
       }
       else {
           JOptionPane.showMessageDialog(this, String.format("Computador jogou %s. Ponto para você.", jogadas[jogadaComputador]));
           pontuacaoJogador++;
           labelPontuacaoJogador.setText(String.format("Você: %s", pontuacaoJogador));
       }
    }//GEN-LAST:event_botaoJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoJogar;
    private javax.swing.JComboBox<String> comboEscolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelPontuacaoComputador;
    private javax.swing.JLabel labelPontuacaoJogador;
    // End of variables declaration//GEN-END:variables
}
